language: ruby
rvm:
- 2.4.2
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
notifications:
  slack:
    secure: CW+tsGgUbdtjVd9d6e6uvoKMeBQ+7EVEMazKOik304MjoVrkIszgZ/1OiH6mxs6tHmDdNM7+VW6iQFKa1p31fJ92ZzAOaFAnSe4KWiQ8BIkQ1OiEeA9NDFC0wp6u+5v2Xojdzx8RVFueMfp8AxG5YRBPyfZFtmeXZSrEdE6YZPU=
