# Site settings
title: Mash Software
author: Mash Software
email: hello@mashsoftware.com
description: Mash Software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mashsoftware.com" # the base hostname & protocol for your site
twitter_username: MashSoftware
github_username:  MashSoftware

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
