# Site settings
title: MASH Software
email: hello@mashsoftware.com
description: MASH Software is the professional identity of Matthew Shaw, a software developer and designer providing digital service design, development and consultancy based in Plymouth, Devon, UK.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mashsoftware.com" # the base hostname & protocol for your site
twitter:
  username: MashSoftware
facebook:
  publisher: 352816538231080
social:
  links:
    - https://twitter.com/MashSoftware
    - https://www.facebook.com/MashSW/
    - https://github.com/MashSoftware
lang: en_GB
sass:
    sass_dir: _sass
    style: compressed

# Custom settings
github_username:  MashSoftware
github_url: https://github.com/
github_repo: mashsoftware.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
