- name: Mash Petitions
  url: http://petitions.mashsoftware.com/
  stage: CLOSED
  description: Mash Petitions is a digital public service that enables users to explore information about UK government and parliament petitions.
  repo: https://github.com/MashSoftware/petitions
  blog: https://medium.com/mash-software/mash-petitions-service-74502e06bb71
- name: Mash Health
  url: https://mash-health.herokuapp.com/
  stage: CLOSED
  description: Mash Health is a digital public service that enables users to find UK healthcare providers.
  repo: https://github.com/MashSoftware/health
  blog: https://medium.com/mash-software/mash-health-20d1f0ff248e
- name: Mash Software
  url: https://www.mashsoftware.com/
  stage: LIVE
  description: Professional website to showcase my work with a consistent brand and identity.
  repo: https://github.com/MashSoftware/mashsoftware.github.io
- name: Starlight Creations
  url: http://www.starlightcreations.co.uk/
  stage: BETA
  description: Professional website for a company that create, sell and rent bespoke art, craft and decorations.
  repo: https://github.com/MashSoftware/mashsoftware.github.io